language: python

python:
  - 2.7
  - 3.3

install:
 - pip install -r dev_requirements.txt --use-mirrors
 - python setup.py develop

before_script:
 - make flake8

script:
 - make test
 - make coverage

after_success:
 - pip install coveralls
 - coveralls
