language: python

env:
 - NPM=./node-v0.10.22-linux-x64/bin/npm
 - GRUNT=./node-v0.10.22-linux-x64/bin/grunt

python:
  - 2.7
  - 3.3

install:
 - wget http://nodejs.org/dist/v0.10.22/node-v0.10.22-linux-x64.tar.gz
 - tar xzvf node-v0.10.22-linux-x64.tar.gz
 - pip install -r dev_requirements.txt --use-mirrors
 - python setup.py develop

before_script:
 - make flake8

script:
 - make test
 - make coverage

after_success:
 - pip install coveralls
 - coveralls
